format = """\
[â•­â•´](fg:$style)\
$username\
$all\
[â•°â”€](fg:$style)$character\
$battery\
"""

[username]
style_user = 'bold os'
style_root = 'bold os_admin'
format = '[îƒ  $user](fg:$style) '
disabled = false
show_always = true

[character]
success_symbol = "[ó°Ÿ](fg:$style)"
error_symbol = "[ âš ](fg:red)"
vimcmd_symbol = '[ó°ŸğŸ„½ ](bold green)'
vimcmd_visual_symbol = "[ó°ŸğŸ…… ](bold fg:red)"
vimcmd_replace_symbol = "[ó°ŸğŸ… ](bold fg:blue)"
vimcmd_replace_one_symbol = "[ó°ŸğŸ… ](bold fg:blue)"

[[battery.display]]
threshold = 20
style = 'bold red'
